import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const browser = await chromium.launch({ executablePath: process.env.BROWSER_EXECUTABLE_PATH || 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
const errors = [];
page.on('pageerror', e => errors.push(e.message));
const skillId = 'ui_check_' + Date.now();
try {
  await page.goto('http://127.0.0.1:5173');
  await page.locator('.workspace-tools button').filter({ hasText: 'Skills' }).click();
  await page.getByRole('dialog', { name: 'Skill library' }).waitFor();
  await page.getByRole('button', { name: 'Create skill', exact: true }).click();
  await page.getByLabel('Skill ID', { exact: true }).fill(skillId);
  await page.getByLabel('Display name', { exact: true }).fill('UI test workflow');
  await page.getByLabel('Skill description', { exact: true }).fill('Local interface acceptance check');
  await page.getByRole('button', { name: 'Save skill', exact: true }).click();
  await page.getByRole('heading', { name: 'UI test workflow', exact: true }).waitFor();
  await page.getByTitle('Edit skill', { exact: true }).click();
  const editor = page.getByLabel('Edit skill Markdown');
  await editor.fill((await editor.inputValue()).replace('Local interface acceptance check', 'Edited interface acceptance check'));
  await page.getByRole('button', { name: 'Save skill', exact: true }).click();
  await page.locator('.skill-document').filter({ hasText: 'Edited interface acceptance check' }).waitFor();
  page.once('dialog', dialog => dialog.accept());
  await page.getByTitle('Delete skill', { exact: true }).click();
  await page.getByRole('button', { name: 'Create skill', exact: true }).waitFor();
  await page.getByRole('button', { name: 'Close skills', exact: true }).click();
  await page.locator('.workspace-tools button').filter({ hasText: 'Files' }).click();
  await page.getByRole('dialog', { name: 'File workspace' }).waitFor();
  await page.locator('.file-list button').filter({ hasText: 'reports' }).click();
  await page.locator('.file-list').filter({ hasText: '.png' }).waitFor();
  await page.getByRole('button', { name: 'Close files', exact: true }).click();
  await page.getByRole('button', { name: 'Acceptance - daily report', exact: true }).last().click();
  await page.getByAltText('Latest real browser screenshot').waitFor();
  await page.getByRole('button', { name: 'Full page', exact: true }).click();
  const image = page.getByAltText('Latest real browser screenshot');
  await image.waitFor({ timeout: 30000 });
  await page.waitForFunction(() => { const image = document.querySelector('.image-size img'); return image?.complete && image.naturalHeight > 2500; });
  await image.click({ position: { x: 20, y: 20 } });
  const viewer = page.getByRole('dialog', { name: 'Screenshot viewer', exact: true });
  await viewer.waitFor();
  await viewer.getByRole('button', { name: 'Reset zoom to 100%', exact: true }).click();
  assert.equal(await viewer.locator('.zoom-value').innerText(), '100%');
  await viewer.getByRole('button', { name: 'Zoom in', exact: true }).click();
  assert.equal(await viewer.locator('.zoom-value').innerText(), '125%');
  await viewer.getByRole('button', { name: 'Zoom out', exact: true }).click();
  assert.equal(await viewer.locator('.zoom-value').innerText(), '100%');
  const canvas = viewer.getByLabel('Screenshot canvas', { exact: true });
  const box = await canvas.boundingBox();
  await page.mouse.move(box.x + 300, box.y + 300);
  await page.mouse.wheel(0, -100);
  await page.waitForFunction(() => document.querySelector('.expanded .zoom-value')?.textContent !== '100%');
  await canvas.evaluate(el => { el.scrollTop = 300; });
  const before = await canvas.evaluate(el => el.scrollTop);
  await page.mouse.move(box.x + 300, box.y + 400);
  await page.mouse.down();
  await page.mouse.move(box.x + 230, box.y + 220, { steps: 8 });
  await page.mouse.up();
  assert.ok(await canvas.evaluate(el => el.scrollTop) > before, 'Dragging pans the tall screenshot');
  await viewer.getByRole('button', { name: 'Fit image', exact: true }).click();
  await canvas.dblclick({ position: { x: 300, y: 300 } });
  assert.equal(await viewer.locator('.zoom-value').innerText(), '100%');
  await viewer.getByRole('button', { name: 'Fit image', exact: true }).click();
  await page.screenshot({ path: 'data/test-artifacts/viewer.png' });
  await page.keyboard.press('Escape');
  await viewer.waitFor({ state: 'detached' });
  await page.getByRole('button', { name: 'Switch to dark mode', exact: true }).click();
  await page.screenshot({ path: 'data/test-artifacts/updated-desktop-dark.png' });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'data/test-artifacts/updated-mobile.png' });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'No horizontal overflow on mobile');
  assert.deepEqual(errors, []);
  console.log('PASS: skill create/view/edit/delete, file listing, actual tall full-page capture, image overlay, zoom in/out/reset, wheel zoom, drag pan, double-click, fit, Escape, dark mode, mobile');
} finally {
  await fetch('http://127.0.0.1:8000/api/skills/' + skillId, { method: 'DELETE' }).catch(() => {});
  await browser.close();
}
